### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by vincentlaucsb** [vincentlaucsb/csv-parser#2]
- [x] Fix memory issues detected by Valgrind
- [ ] Add a reading test using a small CSV file (<50 lines)
- [x] Rewrite parser using string_views/so it doesn't allocate a bunch of vector<string>s
- [ ] Add conversion to Markdown
- [x] Create a single-header version
